/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeamsTeamIdIndexImport } from './routes/teams/$teamId/index'
import { Route as TeamsTeamIdChannelsChannelIdIndexImport } from './routes/teams/$teamId/channels/$channelId/index'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const TeamsTeamIdIndexRoute = TeamsTeamIdIndexImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamIdChannelsChannelIdIndexRoute =
  TeamsTeamIdChannelsChannelIdIndexImport.update({
    id: '/teams/$teamId/channels/$channelId/',
    path: '/teams/$teamId/channels/$channelId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/teams/$teamId/': {
      id: '/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/$teamId/channels/$channelId/': {
      id: '/teams/$teamId/channels/$channelId/'
      path: '/teams/$teamId/channels/$channelId'
      fullPath: '/teams/$teamId/channels/$channelId'
      preLoaderRoute: typeof TeamsTeamIdChannelsChannelIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/channels/$channelId': typeof TeamsTeamIdChannelsChannelIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/teams/$teamId': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/channels/$channelId': typeof TeamsTeamIdChannelsChannelIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/teams/$teamId/': typeof TeamsTeamIdIndexRoute
  '/teams/$teamId/channels/$channelId/': typeof TeamsTeamIdChannelsChannelIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/teams/$teamId'
    | '/teams/$teamId/channels/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/teams/$teamId' | '/teams/$teamId/channels/$channelId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/teams/$teamId/'
    | '/teams/$teamId/channels/$channelId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  TeamsTeamIdIndexRoute: typeof TeamsTeamIdIndexRoute
  TeamsTeamIdChannelsChannelIdIndexRoute: typeof TeamsTeamIdChannelsChannelIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  TeamsTeamIdIndexRoute: TeamsTeamIdIndexRoute,
  TeamsTeamIdChannelsChannelIdIndexRoute:
    TeamsTeamIdChannelsChannelIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/teams/$teamId/",
        "/teams/$teamId/channels/$channelId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/teams/$teamId/": {
      "filePath": "teams/$teamId/index.tsx"
    },
    "/teams/$teamId/channels/$channelId/": {
      "filePath": "teams/$teamId/channels/$channelId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
